function [roboticStructure] = loadRobot(transforms, framesName, jointsType, linksName, mass, MoI, CoM, jointsSymbol)
%LOADROBOT Loads the robot mechanical parameters into a structure 
%   --

roboticStructure = struct( ...
    'DOF',        size(jointsSymbol, 1), ...
    'linksName',  {linksName}, ... 
    'jointsSymbol', {jointsSymbol},... 
    'jointsType', {jointsType},...
    'framesName', {framesName}, ...
    'mass', {mass},...
    'MoI', {MoI},...
    'CoM', {CoM},...
    'T', {transforms},...
    'T_b_i', {cumulateTransforms(transforms)}...
);

roboticStructure.dynamics = struct( ...
    'B', calculateBMatrix(roboticStructure)...
);

roboticStructure.dynamics.C = calculateCMatrix(roboticStructure);
roboticStructure.dynamics.G = calculateGMatrix(roboticStructure);

roboticStructure.eq_motion = roboticStructure.dynamics.B*jointsSymbol(:,3) + roboticStructure.dynamics.C*jointsSymbol(:,2) + roboticStructure.dynamics.G;


end

