function [out] = loadKinematics(transforms, frameNames, jointSymbols, jointTypes)
%LOADKINEMATICS Loads the structure of a robot from a DH table and a simple
%description to calculate its kinematics.
%   --

DOF = size(jointTypes, 2);

out = struct( ...
    'DOF',          DOF, ...
    'joints',       struct('symbols', {jointSymbols}, 'types', {jointTypes}), ...
    'T',            {transforms}, ...
    'frames',      {frameNames} ...
);

end

