function [roboticStructure] = loadRobot(transforms, framesName, jointsType, linksName, MoI, CoM, jointsSymbol)
%LOADROBOT Loads the robot mechanical parameters into a structure 
%   --

roboticStructure = struct( ...
    'DOF',        size(jointsSymbol, 2), ...
    'linksName',  {linksName}, ... 
    'jointsSymbol', {jointsSymbol},... 
    'jointsType', {jointsType},...
    'framesName', {framesName}, ...
    'MoI', {MoI},...
    'CoM', {CoM},...
    'T', {transforms},...
    'T_b_i', {cumulateTransform(transforms)}...
);

roboticStructure.dynamics = struct( ...
    'B', computeBMatrix(roboticStructure) ...
);
roboticStructure.dynamics.C = computeCMatrix(roboticStructure);
roboticStructure.dynamics.G = computeGMatrix(roboticStructure);

roboticStructure.eq_motion = roboticStructure.dynamics.B*jointsSymbol(:,3) + roboticStructure.dynamics.C*jointsSymbol(:,2) + roboticStructure.dynamics.G;
end

